import java.awt.*;

public class Parameters
	{
		public static int THEMES_AMOUNT = 2;
		public static String THEMES_NAMES[] = { "Cars", "Cities" };

		public static String ITEM_NAMES_FILE_PATH[] = { "data/car_names.txt", "data/city_names.txt" };
		public static String ITEM_PHOTO_PATH[] = { "data/car_photo/", "data/city_photo/" };
		public static String RECORDS_FILE_PATH = "data/records.txt";
		public static String DEFAULT_PLAYER_NAME = "Player";

		public static int ANSWER_CASE_AMOUNT = 6;

		public static int MAIN_FRAME_WIDTH = 900, MAIN_FRAME_HEIGHT = 700;

		public static int TABS_LEFT = 0, TABS_TOP = 0, TABS_WIDTH = MAIN_FRAME_WIDTH-10, TABS_HEIGHT = MAIN_FRAME_HEIGHT-35;

		public static int START_BUTTON_WIDTH = 100, START_BUTTON_HEIGHT = 30;
		public static int START_BUTTON_LEFT = 3*TABS_WIDTH/4 - START_BUTTON_WIDTH/2;
		public static int START_BUTTON_TOP = TABS_HEIGHT/2 - START_BUTTON_HEIGHT/2;

		public static int OK_BUTTON_WIDTH = 100, OK_BUTTON_HEIGHT = 30;
		public static int OK_BUTTON_LEFT = TABS_WIDTH - OK_BUTTON_WIDTH - 10;
		public static int OK_BUTTON_TOP = TABS_HEIGHT - 2*OK_BUTTON_HEIGHT;

		public static int GAMER_NAME_TEXTFIELD_WIDTH = 200, GAMER_NAME_TEXTFIELD_HEIGHT = 20;
		public static int GAMER_NAME_TEXTFIELD_LEFT = TABS_WIDTH/4 - GAMER_NAME_TEXTFIELD_WIDTH/2;
		public static int GAMER_NAME_TEXTFIELD_TOP = 100;

		public static int QUESTION_AMOUNT_TEXTFIELD_WIDTH = 200, QUESTION_AMOUNT_TEXTFIELD_HEIGHT = 20;
		public static int QUESTION_AMOUNT_TEXTFIELD_LEFT = TABS_WIDTH/4 - QUESTION_AMOUNT_TEXTFIELD_WIDTH/2;
		public static int QUESTION_AMOUNT_TEXTFIELD_TOP = GAMER_NAME_TEXTFIELD_TOP + 2*QUESTION_AMOUNT_TEXTFIELD_HEIGHT;

		public static int THEME_CHECK_WIDTH = 200, THEME_CHECK_HEIGHT = 20;
		public static int THEME_CHECK_LEFT = TABS_WIDTH/4 - THEME_CHECK_WIDTH/2, THEME_CHECK_TOP = QUESTION_AMOUNT_TEXTFIELD_TOP + 2*THEME_CHECK_HEIGHT;

		public static int PROGRESS_BAR_WIDTH = TABS_WIDTH-200, PROGRESS_BAR_HEIGHT = 20;
		public static int PROGRESS_BAR_LEFT = TABS_WIDTH/2 - PROGRESS_BAR_WIDTH/2, PROGRESS_BAR_TOP = 5*PROGRESS_BAR_HEIGHT/2;

		public static int ANSWER_CASE_WIDTH = 120, ANSWER_CASE_HEIGHT = 30;
		public static int ANSWER_CASE_LEFT = (TABS_WIDTH - (TABS_WIDTH-OK_BUTTON_LEFT) - ANSWER_CASE_WIDTH*ANSWER_CASE_AMOUNT)/2;
		public static int ANSWER_CASE_TOP = TABS_HEIGHT - 2*ANSWER_CASE_HEIGHT;

		public static int CAR_PHOTO_WIDTH = 640, CAR_PHOTO_HEIGHT = 480;
		public static int CAR_PHOTO_LEFT = TABS_WIDTH/2 - CAR_PHOTO_WIDTH/2, CAR_PHOTO_TOP = TABS_HEIGHT/2 - CAR_PHOTO_HEIGHT/2;

		public static int RESULT_LABEL_WIDTH = 400, RESULT_LABEL_HEIGHT = 50;
		public static int RESULT_LABEL_LEFT = TABS_WIDTH/2 - RESULT_LABEL_WIDTH/2, RESULT_LABEL_TOP = TABS_HEIGHT/2 - RESULT_LABEL_HEIGHT/2;
		public static Font RESULT_LABEL_FONT = new Font(null, Font.PLAIN, 30);

		public static int NEW_GAME_BUTTON_LEFT = 10, NEW_GAME_BUTTON_TOP = 10, NEW_GAME_BUTTON_WIDTH = 100, NEW_GAME_BUTTON_HEIGHT = 30;

		public static int RECORDS_LINE_AMOUNT = 15;
		public static int RECORDS_POSITION_LEFT = 160, RECORDS_POSITION_WIDTH = 20;
		public static int RECORDS_NAME_LEFT = RECORDS_POSITION_LEFT + RECORDS_POSITION_WIDTH, RECORDS_NAME_WIDTH = 300;
		public static int RECORDS_PERCENT_LEFT = RECORDS_NAME_LEFT + RECORDS_NAME_WIDTH, RECORDS_PERCENT_WIDTH = 250;
		public static int RECORDS_LINE_TOP = 50, RECORDS_LINE_HEIGHT = 30;

		public static int DELETE_RECORDS_BUTTON_WIDTH = 150, DELETE_RECORDS_BUTTON_HEIGHT = 30;
		public static int DELETE_RECORDS_BUTTON_LEFT = TABS_WIDTH/2 - DELETE_RECORDS_BUTTON_WIDTH/2;
		public static int DELETE_RECORDS_BUTTON_TOP = RECORDS_LINE_TOP + (RECORDS_LINE_AMOUNT+3)*RECORDS_LINE_HEIGHT;

		public static Font RECORD_LABEL_FONT = new Font(null, Font.PLAIN, 20);

		public static boolean WITH_UPDATING_INTERFACE = true, WITHOUT_UPDATING_INTERFACE = false;
	}